 (defun fibonacci()  
 (format t "Enter the limit : ")  
 (setf n(read))  
 (format t "Fibonacci Series : ")  
 (format t "0 1")  
 (setf a 0)  
 (setf b 1)  
 (do ((i 3(+ i 1))) ((> i n))  
  (setf c (+ a b))  
  (format t " ~d" c)  
  (setf a b)  
  (setf b c))) 
